### ISSUE TITLE
怎么使用，我还是不清楚。文档写的是拉取你给的项目、然后安装包，但是怎么用在我自己的项目上呢？是要把你的文件搬到自己的项目上吗？

### ISSUE THREAD

**Issue by liuyeqing** [unitwk/zh-cn-i18n-converter#5]

**Comment by yumao233** [comment]
clone这个项目，进入，再执行 npm start exec ./zh_cn.json <你的项目路径>/hello.vue

**Comment by liuyeqing** [comment]
> clone这个项目，进入，再执行 npm start exec ./zh_cn.json <你的项目路径>/hello.vue

哦哦，真是不好意思，昨天居然没看懂，不知道最后1个参数是可以用绝对路径了。（昨天大概是自己潜意识以为要写相对路径了）
