### ISSUE TITLE
可以给文件夹下的所有文件一次性转换吗？

### ISSUE THREAD

**Issue by liuyeqing** [unitwk/zh-cn-i18n-converter#6]

**Comment by yumao233** [comment]
npm start exec ./zh_cn.json /Users/unitwk/my-project/ 

不填写最后的文件名就默认转换这个目录下的所有文件，但是不会深入到二级目录。

**Comment by liuyeqing** [comment]
> npm start exec ./zh_cn.json /Users/unitwk/my-project/
> 
> 不填写最后的文件名就默认转换这个目录下的所有文件，但是不会深入到二级目录。

嗯嗯，好的。目前我是自己用js（深度遍历目录下的vue、js文件）生成sh文件，sh文件里有一个个的‘npm start exec ./zh_cn.json 文件名’，再运行sh文件来实现对文件夹下所有文件的语言转换。请问你有其他方案吗？
